// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetailedDockerImagesData() {
  return window['go']['bindings']['DockerCommandBindings']['GetDetailedDockerImagesData']();
}

export function ListDockerImages() {
  return window['go']['bindings']['DockerCommandBindings']['ListDockerImages']();
}

export function RestartDockerContainer(arg1) {
  return window['go']['bindings']['DockerCommandBindings']['RestartDockerContainer'](arg1);
}

export function StartDockerContainer(arg1) {
  return window['go']['bindings']['DockerCommandBindings']['StartDockerContainer'](arg1);
}

export function StopDockerContainer(arg1) {
  return window['go']['bindings']['DockerCommandBindings']['StopDockerContainer'](arg1);
}
