// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetDetailedDockerImagesData():Promise<Array<models.DockerContainerData>>;

export function ListDockerImages():Promise<Array<models.DockerImage>>;
