// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContainerLogs(arg1, arg2, arg3) {
  return window['go']['bindings']['DockerCommandBindings']['GetContainerLogs'](arg1, arg2, arg3);
}

export function GetDetailedDockerImagesData(arg1) {
  return window['go']['bindings']['DockerCommandBindings']['GetDetailedDockerImagesData'](arg1);
}

export function ListDockerImages(arg1) {
  return window['go']['bindings']['DockerCommandBindings']['ListDockerImages'](arg1);
}

export function RestartDockerContainer(arg1, arg2) {
  return window['go']['bindings']['DockerCommandBindings']['RestartDockerContainer'](arg1, arg2);
}

export function StartDockerContainer(arg1, arg2) {
  return window['go']['bindings']['DockerCommandBindings']['StartDockerContainer'](arg1, arg2);
}

export function StopDockerContainer(arg1, arg2) {
  return window['go']['bindings']['DockerCommandBindings']['StopDockerContainer'](arg1, arg2);
}
