// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetContainerLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetDetailedDockerImagesData(arg1:string):Promise<Array<models.DockerContainerData>>;

export function ListDockerImages(arg1:string):Promise<Array<models.DockerImage>>;

export function RestartDockerContainer(arg1:string,arg2:string):Promise<boolean>;

export function StartDockerContainer(arg1:string,arg2:string):Promise<boolean>;

export function StopDockerContainer(arg1:string,arg2:string):Promise<boolean>;
