// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetailedDockerImagesData() {
  return window['go']['bindings']['DockerCommandBindings']['GetDetailedDockerImagesData']();
}

export function ListDockerImages() {
  return window['go']['bindings']['DockerCommandBindings']['ListDockerImages']();
}
