// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddHost(arg1:models.Host):Promise<boolean>;

export function GetHosts():Promise<Array<models.Host>>;
