// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['bindings']['HostBindings']['AddHost'](arg1);
}

export function GetHosts() {
  return window['go']['bindings']['HostBindings']['GetHosts']();
}
