// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHostStats(arg1) {
  return window['go']['bindings']['HostStatsBindings']['GetHostStats'](arg1);
}
