// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docker_commands} from '../models';

export function ListDockerImages():Promise<Array<docker_commands.DockerImage>>;
